package com.eurogames.domain.usecase.auth

import com.eurogames.Result
import com.eurogames.domain.model.User
import com.eurogames.domain.model.auth.SignUpFormData
import com.eurogames.domain.repository.AuthRepository

class SignUpUseCase(private val repository: AuthRepository) {
    suspend operator fun invoke(user: SignUpFormData): Result<User> {
        val newUser = User(
            id = 0, // Assuming the ID is auto-generated by the database
            username = user.username,
            email = user.email,
            password = user.password,
            fullName = user.fullName
        )
        return repository.signUp(newUser)
    }
}